<?php

namespace Proxies\__CG__\Eva\AdminBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \Eva\AdminBundle\Entity\Product implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Eva\\AdminBundle\\Entity\\Product' . "\0" . 'id', '' . "\0" . 'Eva\\AdminBundle\\Entity\\Product' . "\0" . 'name', '' . "\0" . 'Eva\\AdminBundle\\Entity\\Product' . "\0" . 'reference', '' . "\0" . 'Eva\\AdminBundle\\Entity\\Product' . "\0" . 'quantity', '' . "\0" . 'Eva\\AdminBundle\\Entity\\Product' . "\0" . 'description', '' . "\0" . 'Eva\\AdminBundle\\Entity\\Product' . "\0" . 'userGuide', '' . "\0" . 'Eva\\AdminBundle\\Entity\\Product' . "\0" . 'composition', '' . "\0" . 'Eva\\AdminBundle\\Entity\\Product' . "\0" . 'price', '' . "\0" . 'Eva\\AdminBundle\\Entity\\Product' . "\0" . 'dateCreation', '' . "\0" . 'Eva\\AdminBundle\\Entity\\Product' . "\0" . 'video', '' . "\0" . 'Eva\\AdminBundle\\Entity\\Product' . "\0" . 'subCategory', '' . "\0" . 'Eva\\AdminBundle\\Entity\\Product' . "\0" . 'marque', '' . "\0" . 'Eva\\AdminBundle\\Entity\\Product' . "\0" . 'images', '' . "\0" . 'Eva\\AdminBundle\\Entity\\Product' . "\0" . 'tags', '' . "\0" . 'Eva\\AdminBundle\\Entity\\Product' . "\0" . 'nbSales', '' . "\0" . 'Eva\\AdminBundle\\Entity\\Product' . "\0" . 'offers', '' . "\0" . 'Eva\\AdminBundle\\Entity\\Product' . "\0" . 'defaultImage', '' . "\0" . 'Eva\\AdminBundle\\Entity\\Product' . "\0" . 'availableOffer'];
        }

        return ['__isInitialized__', '' . "\0" . 'Eva\\AdminBundle\\Entity\\Product' . "\0" . 'id', '' . "\0" . 'Eva\\AdminBundle\\Entity\\Product' . "\0" . 'name', '' . "\0" . 'Eva\\AdminBundle\\Entity\\Product' . "\0" . 'reference', '' . "\0" . 'Eva\\AdminBundle\\Entity\\Product' . "\0" . 'quantity', '' . "\0" . 'Eva\\AdminBundle\\Entity\\Product' . "\0" . 'description', '' . "\0" . 'Eva\\AdminBundle\\Entity\\Product' . "\0" . 'userGuide', '' . "\0" . 'Eva\\AdminBundle\\Entity\\Product' . "\0" . 'composition', '' . "\0" . 'Eva\\AdminBundle\\Entity\\Product' . "\0" . 'price', '' . "\0" . 'Eva\\AdminBundle\\Entity\\Product' . "\0" . 'dateCreation', '' . "\0" . 'Eva\\AdminBundle\\Entity\\Product' . "\0" . 'video', '' . "\0" . 'Eva\\AdminBundle\\Entity\\Product' . "\0" . 'subCategory', '' . "\0" . 'Eva\\AdminBundle\\Entity\\Product' . "\0" . 'marque', '' . "\0" . 'Eva\\AdminBundle\\Entity\\Product' . "\0" . 'images', '' . "\0" . 'Eva\\AdminBundle\\Entity\\Product' . "\0" . 'tags', '' . "\0" . 'Eva\\AdminBundle\\Entity\\Product' . "\0" . 'nbSales', '' . "\0" . 'Eva\\AdminBundle\\Entity\\Product' . "\0" . 'offers', '' . "\0" . 'Eva\\AdminBundle\\Entity\\Product' . "\0" . 'defaultImage', '' . "\0" . 'Eva\\AdminBundle\\Entity\\Product' . "\0" . 'availableOffer'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Product $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getDefaultImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultImage', []);

        return parent::getDefaultImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setDefaultImage($defaultImage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDefaultImage', [$defaultImage]);

        return parent::setDefaultImage($defaultImage);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantity', []);

        return parent::getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function getComposition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComposition', []);

        return parent::getComposition();
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreation', []);

        return parent::getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function getVideo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVideo', []);

        return parent::getVideo();
    }

    /**
     * {@inheritDoc}
     */
    public function getSubCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubCategory', []);

        return parent::getSubCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function getMarque()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarque', []);

        return parent::getMarque();
    }

    /**
     * {@inheritDoc}
     */
    public function getImages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImages', []);

        return parent::getImages();
    }

    /**
     * {@inheritDoc}
     */
    public function getTags()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTags', []);

        return parent::getTags();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantity($quantity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantity', [$quantity]);

        return parent::setQuantity($quantity);
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function setComposition($composition)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComposition', [$composition]);

        return parent::setComposition($composition);
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreation(\DateTime $dateCreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreation', [$dateCreation]);

        return parent::setDateCreation($dateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function setVideo($video)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVideo', [$video]);

        return parent::setVideo($video);
    }

    /**
     * {@inheritDoc}
     */
    public function setSubCategory($subCategory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubCategory', [$subCategory]);

        return parent::setSubCategory($subCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function setMarque($marque)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarque', [$marque]);

        return parent::setMarque($marque);
    }

    /**
     * {@inheritDoc}
     */
    public function setImages($images)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImages', [$images]);

        return parent::setImages($images);
    }

    /**
     * {@inheritDoc}
     */
    public function setTags($tags)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTags', [$tags]);

        return parent::setTags($tags);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbSales()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbSales', []);

        return parent::getNbSales();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbSales($nbSales)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbSales', [$nbSales]);

        return parent::setNbSales($nbSales);
    }

    /**
     * {@inheritDoc}
     */
    public function getReference()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReference', []);

        return parent::getReference();
    }

    /**
     * {@inheritDoc}
     */
    public function getUserGuide()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserGuide', []);

        return parent::getUserGuide();
    }

    /**
     * {@inheritDoc}
     */
    public function getOffers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOffers', []);

        return parent::getOffers();
    }

    /**
     * {@inheritDoc}
     */
    public function setReference($reference)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReference', [$reference]);

        return parent::setReference($reference);
    }

    /**
     * {@inheritDoc}
     */
    public function setUserGuide($userGuide)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserGuide', [$userGuide]);

        return parent::setUserGuide($userGuide);
    }

    /**
     * {@inheritDoc}
     */
    public function setOffers($offers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOffers', [$offers]);

        return parent::setOffers($offers);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getAvailableOffer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvailableOffer', []);

        return parent::getAvailableOffer();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvailableOffer($availableOffer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvailableOffer', [$availableOffer]);

        return parent::setAvailableOffer($availableOffer);
    }

}
