services:
    acme_user.registration.form.type:
        class: Eva\ClientBundle\Form\User\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: acme_user_registration }
